// Photos
import Product_01 from "../../../assets/images/Products/Product_01.png";
import Product_02 from "../../../assets/images/Products/Product_02.png";
import Product_03 from "../../../assets/images/Products/Product_03.png";
import Product_04 from "../../../assets/images/Products/Product_04.png";
import Product_05 from "../../../assets/images/Products/Product_05.png";
import Product_06 from "../../../assets/images/Products/Product_06.png";
import Product_07 from "../../../assets/images/Products/Product_07.png";
import Product_08 from "../../../assets/images/Products/Product_08.png";
import Product_09 from "../../../assets/images/Products/Product_09.png";
import Product_10 from "../../../assets/images/Products/Product_10.png";
import Product_11 from "../../../assets/images/Products/Product_11.png";

import Slider_01 from "../../../assets/images/Sliders/Slider_01.jpg";
import Slider_02 from "../../../assets/images/Sliders/Slider_02.jpg";
import Slider_03 from "../../../assets/images/Sliders/Slider_03.jpg";
import Slider_05 from "../../../assets/images/Sliders/Slider_05.jpg";
import Slider_06 from "../../../assets/images/Sliders/Slider_06.jpg";
import Slider_07 from "../../../assets/images/Sliders/Slider_07.jpg";

// React Icons
import { CiMedal, CiDeliveryTruck, CiWallet } from "react-icons/ci";
import { PiHandbagSimpleLight } from "react-icons/pi";

export const benefits = [
  {
    _id: "1",
    image: CiMedal,
    titleKey: "benefitsSection.onlineSupport",
    descriptionKey: "benefitsSection.onlineSupportDesc",
  },
  {
    _id: "2",
    image: CiDeliveryTruck,
    titleKey: "benefitsSection.freeShipping",
    descriptionKey: "benefitsSection.freeShippingDesc",
  },
  {
    _id: "3",
    image: CiWallet,
    titleKey: "benefitsSection.moneyReturn",
    descriptionKey: "benefitsSection.moneyReturnDesc",
  },
  {
    _id: "4",
    image: PiHandbagSimpleLight,
    titleKey: "benefitsSection.memberDiscount",
    descriptionKey: "benefitsSection.memberDiscountDesc",
  },
];

export const productSection_01 = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€359",
    title: "productSection_01.title_01",
    description: "productSection_01.decription_01",
    quantity: "25",
    available: "productSection_01.available",
    quantitySold: "5",
    sold: "productSection_01.sold",
    info: "productSection_01.info",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "2.5",
    normalPrice: "€2799",
    title: "productSection_01.title_02",
    quantity: "30",
    available: "productSection_01.available",
    quantitySold: "15",
    sold: "productSection_01.sold",
    info: "productSection_01.info",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "3.5",
    normalPrice: "€799",
    title: "productSection_01.title_03",
    quantity: "20",
    available: "productSection_01.available",
    quantitySold: "7",
    sold: "productSection_01.sold",
    info: "productSection_01.info",
  },
];

export const computers = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€179",
    title: "Sony A7 III Mirrorless Camera with 4K Video",
    available: "25",
    sold: "5",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "5.0",
    normalPrice: "€2799",
    title: "GeForce RTX 3060 Ti Gaming OC PRO 8Gb",
    available: "16",
    sold: "14",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "4",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "5",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "6",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
];

export const mobilesAndTablets = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€179",
    title: "mobilesAndTablets.title_01",
    available: "25",
    sold: "5",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "5.0",
    normalPrice: "€2799",
    title: "mobilesAndTablets.title_02",
    available: "16",
    sold: "14",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_03",
    available: "12",
    sold: "2",
  },
  {
    _id: "4",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_04",
    available: "12",
    sold: "2",
  },
  {
    _id: "5",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_05",
    available: "12",
    sold: "2",
  },
  {
    _id: "6",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_06",
    available: "12",
    sold: "2",
  },
  {
    _id: "7",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_07",
    available: "12",
    sold: "2",
  },
  {
    _id: "8",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_08",
    available: "12",
    sold: "2",
  },
  {
    _id: "9",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "mobilesAndTablets.title_09",
    available: "12",
    sold: "2",
  },
];

export const gameAccessories = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€179",
    title: "Sony A7 III Mirrorless Camera with 4K Video",
    available: "25",
    sold: "5",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "5.0",
    normalPrice: "€2799",
    title: "GeForce RTX 3060 Ti Gaming OC PRO 8Gb",
    available: "16",
    sold: "14",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
];

export const cameraAndPhoto = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€179",
    title: "Sony A7 III Mirrorless Camera with 4K Video",
    available: "25",
    sold: "5",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "5.0",
    normalPrice: "€2799",
    title: "GeForce RTX 3060 Ti Gaming OC PRO 8Gb",
    available: "16",
    sold: "14",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "4",
    image: Product_07,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
];

export const electronics = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€179",
    title: "Sony A7 III Mirrorless Camera with 4K Video",
    available: "25",
    sold: "5",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "5.0",
    normalPrice: "€2799",
    title: "GeForce RTX 3060 Ti Gaming OC PRO 8Gb",
    available: "16",
    sold: "14",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "4",
    image: Product_05,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
];

export const audioAndHeadphones = [
  {
    _id: "1",
    image: Product_05,
    rating: "2.0",
    normalPrice: "€179",
    title: "Sony A7 III Mirrorless Camera with 4K Video",
    available: "25",
    sold: "5",
  },
  {
    _id: "2",
    image: Product_04,
    rating: "5.0",
    normalPrice: "€2799",
    title: "GeForce RTX 3060 Ti Gaming OC PRO 8Gb",
    available: "16",
    sold: "14",
  },
  {
    _id: "3",
    image: Product_03,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "4",
    image: Product_05,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
  {
    _id: "5",
    image: Product_07,
    rating: "4.0",
    normalPrice: "€799",
    title: "Console PlayStation®5 Pro Digital 2TB",
    available: "12",
    sold: "2",
  },
];

export const shopByCategories = [
  {
    _id: "1",
    image: Product_03,
    title: "productSection_04.title_01",
    quantity: computers.length,
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "Ryzen 7 5800H up to 4.40GHz",
    detail_02: "RTX 3070 8GB GDDR6 Graphics",
    detail_03: "12GB DDR4 RAM + 4TB NVMe SSD",
    detail_04: "Windows 11 Professional (64bit)",
    rating: "3.0",
    reviews: "3 Customer Reviews",
  },
  {
    _id: "2",
    image: Product_08,
    title: "productSection_04.title_02",
    quantity: mobilesAndTablets.length,
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "Ryzen 7 5800H up to 4.40GHz",
    detail_02: "RTX 3070 8GB GDDR6 Graphics",
    detail_03: "12GB DDR4 RAM + 4TB NVMe SSD",
    detail_04: "Windows 11 Professional (64bit)",
    rating: "3.0",
    reviews: "3 Customer Reviews",
  },
  {
    _id: "3",
    image: Product_07,
    title: "productSection_04.title_03",
    quantity: gameAccessories.length,
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "Ryzen 7 5800H up to 4.40GHz",
    detail_02: "RTX 3070 8GB GDDR6 Graphics",
    detail_03: "12GB DDR4 RAM + 4TB NVMe SSD",
    detail_04: "Windows 11 Professional (64bit)",
    rating: "3.0",
    reviews: "3 Customer Reviews",
  },
  {
    _id: "4",
    image: Product_11,
    title: "productSection_04.title_04",
    quantity: cameraAndPhoto.length,
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "Ryzen 7 5800H up to 4.40GHz",
    detail_02: "RTX 3070 8GB GDDR6 Graphics",
    detail_03: "12GB DDR4 RAM + 4TB NVMe SSD",
    detail_04: "Windows 11 Professional (64bit)",
    rating: "3.0",
    reviews: "3 Customer Reviews",
  },
  {
    _id: "5",
    image: Product_09,
    title: "productSection_04.title_05",
    quantity: electronics.length,
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "Ryzen 7 5800H up to 4.40GHz",
    detail_02: "RTX 3070 8GB GDDR6 Graphics",
    detail_03: "12GB DDR4 RAM + 4TB NVMe SSD",
    detail_04: "Windows 11 Professional (64bit)",
    rating: "3.0",
    reviews: "3 Customer Reviews",
  },
  {
    _id: "6",
    image: Product_10,
    title: "productSection_04.title_06",
    quantity: audioAndHeadphones.length,
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "Ryzen 7 5800H up to 4.40GHz",
    detail_02: "RTX 3070 8GB GDDR6 Graphics",
    detail_03: "12GB DDR4 RAM + 4TB NVMe SSD",
    detail_04: "Windows 11 Professional (64bit)",
    rating: "3.0",
    reviews: "3 Customer Reviews",
  },
];

export const productSection_03 = [
  {
    _id: "1",
    image: Product_01,
    title_02: "productSection_03.title_02",
    title_01: "productSection_03.title_01",
    description: "productSection_03.description",
    button: "productSection_03.button",
  },
  {
    _id: "2",
    image: Product_04,
    title_02: "productSection_03.title_02",
    title_01: "productSection_03.title_01",
    description: "productSection_03.description",
    button: "productSection_03.button",
  },
];

export const productSection_05 = [
  {
    _id: "1",
    image: Product_01,
    rating: "3.0",
    title: "productSection_05.title_01",
    description: "productSection_05.description_01",
    normalPrice: "€1169",
    offerPrice: "€839",
  },
  {
    _id: "2",
    image: Product_02,
    rating: "5.0",
    title: "productSection_05.title_02",
    description: "productSection_05.description_02",
    normalPrice: "€1169",
    offerPrice: "€939",
  },
  {
    _id: "3",
    image: Product_04,
    rating: "3.0",
    title: "productSection_05.title_03",
    description: "productSection_05.description_03",
    normalPrice: "€769",
    offerPrice: "€539",
  },
  {
    _id: "4",
    image: Product_06,
    rating: "4.0",
    title: "productSection_05.title_04",
    description: "productSection_05.description_04",
    normalPrice: "€69",
    offerPrice: "€39",
  },
];

export const productSection_06 = [
  {
    _id: "1",
    image: Product_01,
    rating: "3.0",
    title: "productSection_06.title_01",
    description: "productSection_06.description_01",
    normalPrice: "€1169",
    offerPrice: "€839",
  },
  {
    _id: "2",
    image: Product_02,
    rating: "5.0",
    title: "productSection_06.title_02",
    description: "productSection_06.description_02",
    normalPrice: "€1169",
    offerPrice: "€939",
  },
  {
    _id: "3",
    image: Product_04,
    rating: "3.0",
    title: "productSection_06.title_03",
    description: "productSection_06.description_03",
    normalPrice: "€769",
    offerPrice: "€539",
  },
  {
    _id: "4",
    image: Product_06,
    rating: "4.0",
    title: "productSection_06.title_04",
    description: "productSection_06.description_04",
    normalPrice: "€69",
    offerPrice: "€39",
  },
  {
    _id: "5",
    image: Product_08,
    rating: "4.0",
    title: "productSection_06.title_05",
    description: "productSection_06.description_05",
    normalPrice: "€69",
    offerPrice: "€39",
  },
  {
    _id: "6",
    image: Product_03,
    rating: "4.0",
    title: "productSection_06.title_06",
    description: "productSection_06.description_06",
    normalPrice: "€69",
    offerPrice: "€39",
  },
  {
    _id: "7",
    image: Product_05,
    rating: "4.0",
    title: "productSection_06.title_07",
    description: "productSection_06.description_07",
    normalPrice: "€69",
    offerPrice: "€39",
  },
  {
    _id: "8",
    image: Product_04,
    rating: "4.0",
    title: "productSection_06.title_08",
    description: "productSection_06.description_08",
    normalPrice: "€69",
    offerPrice: "€39",
  },
];

export const latestProducts = [
  {
    _id: "1",
    image: Product_01,
    title: "product_01.title",
    description: "product_01.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_01.detail_01",
    detail_02: "product_01.detail_02",
    detail_03: "product_01.detail_03",
    detail_04: "product_01.detail_04",
    rating: "3.0",
    reviews: "product_01.review",
    addToCart: "product_01.addToCart"
  },
  {
    _id: "2",
    image: Product_02,
    title: "product_02.title",
    description: "product_02.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_02.detail_01",
    detail_02: "product_02.detail_02",
    detail_03: "product_02.detail_03",
    detail_04: "product_02.detail_04",
    rating: "3.0",
    reviews: "product_02.review",
    addToCart: "product_02.addToCart"
  },
  {
    _id: "3",
    image: Product_03,
    title: "product_03.title",
    description: "product_03.description",
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "product_03.detail_01",
    detail_02: "product_03.detail_02",
    detail_03: "product_03.detail_03",
    detail_04: "product_03.detail_04",
    rating: "3.0",
    reviews: "product_03.review",
    addToCart: "product_03.addToCart"
  },
  {
    _id: "4",
    image: Product_04,
    title: "product_04.title",
    description: "product_04.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_04.detail_01",
    detail_02: "product_04.detail_02",
    detail_03: "product_04.detail_03",
    detail_04: "product_04.detail_04",
    rating: "3.0",
    reviews: "product_04.review",
    addToCart: "product_04.addToCart"
  },
  {
    _id: "5",
    image: Product_05,
    title: "product_05.title",
    description: "product_05.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_05.detail_01",
    detail_02: "product_05.detail_02",
    detail_03: "product_05.detail_03",
    detail_04: "product_05.detail_04",
    rating: "4.0",
    review: "product_05.review",
    addToCart: "product_05.addToCart"
  },
  {
    _id: "6",
    image: Product_06,
    title: "product_06.title",
    description: "product_06.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_06.detail_01",
    detail_02: "product_06.detail_02",
    detail_03: "product_06.detail_03",
    detail_04: "product_06.detail_04",
    rating: "3.0",
    reviews: "product_06.review",
  },
];

export const bestSelling = [
  {
    _id: "1",
    image: Product_02,
    title: "product_02.title",
    description: "product_02.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_02.detail_01",
    detail_02: "product_02.detail_02",
    detail_03: "product_02.detail_03",
    detail_04: "product_02.detail_04",
    rating: "3.0",
    reviews: "product_02.review",
    addToCart: "product_02.addToCart"
  },
  {
    _id: "2",
    image: Product_05,
    title: "product_05.title",
    description: "product_05.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_05.detail_01",
    detail_02: "product_05.detail_02",
    detail_03: "product_05.detail_03",
    detail_04: "product_05.detail_04",
    rating: "4.0",
    review: "product_05.review",
    addToCart: "product_05.addToCart"
  },
  {
    _id: "3",
    image: Product_03,
    title: "product_03.title",
    description: "product_03.description",
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "product_03.detail_01",
    detail_02: "product_03.detail_02",
    detail_03: "product_03.detail_03",
    detail_04: "product_03.detail_04",
    rating: "3.0",
    reviews: "product_03.review",
    addToCart: "product_03.addToCart"
  },
  {
    _id: "4",
    image: Product_04,
    title: "product_04.title",
    description: "product_04.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_04.detail_01",
    detail_02: "product_04.detail_02",
    detail_03: "product_04.detail_03",
    detail_04: "product_04.detail_04",
    rating: "3.0",
    reviews: "product_04.review",
    addToCart: "product_04.addToCart"
  },
  {
    _id: "5",
    image: Product_06,
    title: "product_06.title",
    description: "product_06.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_06.detail_01",
    detail_02: "product_06.detail_02",
    detail_03: "product_06.detail_03",
    detail_04: "product_06.detail_04",
    rating: "3.0",
    reviews: "product_06.review",
    addToCart: "product_06.addToCart"
  },
  {
    _id: "6",
    image: Product_01,
    title: "product_01.title",
    description: "product_01.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_01.detail_01",
    detail_02: "product_01.detail_02",
    detail_03: "product_01.detail_03",
    detail_04: "product_01.detail_04",
    rating: "3.0",
    reviews: "product_01.review",
    addToCart: "product_01.addToCart"
  },
];

export const topRating = [
  {
    _id: "1",
    image: Product_03,
    title: "product_03.title",
    description: "product_03.description",
    normalPrice: "€959",
    offerPrice: "€539",
    detail_01: "product_03.detail_01",
    detail_02: "product_03.detail_02",
    detail_03: "product_03.detail_03",
    detail_04: "product_03.detail_04",
    rating: "3.0",
    reviews: "product_03.review",
    addToCart: "product_03.addToCart"
  },
  {
    _id: "2",
    image: Product_04,
    title: "product_04.title",
    description: "product_04.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_04.detail_01",
    detail_02: "product_04.detail_02",
    detail_03: "product_04.detail_03",
    detail_04: "product_04.detail_04",
    rating: "3.0",
    reviews: "product_04.review",
    addToCart: "product_04.addToCart"
  },
  {
    _id: "3",
    image: Product_01,
    title: "product_01.title",
    description: "product_01.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_01.detail_01",
    detail_02: "product_01.detail_02",
    detail_03: "product_01.detail_03",
    detail_04: "product_01.detail_04",
    rating: "3.0",
    reviews: "product_01.review",
    addToCart: "product_01.addToCart"
  },
  {
    _id: "4",
    image: Product_05,
    title: "product_05.title",
    description: "product_05.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_05.detail_01",
    detail_02: "product_05.detail_02",
    detail_03: "product_05.detail_03",
    detail_04: "product_05.detail_04",
    rating: "5.0",
    reviews: "product_05.review",
    addToCart: "product_05.addToCart"
  },
  {
    _id: "5",
    image: Product_06,
    title: "product_06.title",
    description: "product_06.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_06.detail_01",
    detail_02: "product_06.detail_02",
    detail_03: "product_06.detail_03",
    detail_04: "product_06.detail_04",
    rating: "3.0",
    reviews: "product_06.review",
    addToCart: "product_06.addToCart"
  },
  {
    _id: "6",
    image: Product_02,
    title: "product_02.title",
    description: "product_02.description",
    normalPrice: "€759",
    offerPrice: "€639",
    detail_01: "product_02.detail_01",
    detail_02: "product_02.detail_02",
    detail_03: "product_02.detail_03",
    detail_04: "product_02.detail_04",
    rating: "3.0",
    reviews: "product_02.review",
    addToCart: "product_02.addToCart"
  },
];

export const carousel_01 = [
  {
    _id: "1",
    image: Slider_01,
    discount: "carousel_01.discount_01",
    title: "carousel_01.title_01",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_01",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
  {
    _id: "2",
    image: Slider_01,
    discount: "carousel_01.discount_02",
    title: "carousel_01.title_02",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_02",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
];

export const carousel_02 = [
  {
    _id: "1",
    image: Slider_02,
  },
  {
    _id: "2",
    image: Slider_02,
  },
];

export const carousel_03 = [
  {
    _id: "1",
    image: Slider_03,
    discount: "carousel_01.discount_01",
    title: "carousel_01.title_01",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_01",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
  {
    _id: "2",
    image: Slider_06,
    discount: "carousel_01.discount_02",
    title: "carousel_01.title_02",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_02",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
];

export const carousel_04 = [
  {
    _id: "1",
    image: Slider_07,
    discount: "carousel_01.discount_01",
    title: "carousel_01.title_01",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_01",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
  {
    _id: "2",
    image: Slider_05,
    discount: "carousel_01.discount_02",
    title: "carousel_01.title_02",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_02",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
];

export const carousel_05 = [
  {
    _id: "1",
    image: Slider_07,
    discount: "carousel_01.discount_01",
    title: "carousel_01.title_01",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_01",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
  {
    _id: "2",
    image: Slider_05,
    discount: "carousel_01.discount_02",
    title: "carousel_01.title_02",
    addToCart: "carousel_01.addToCart",
    paragraph: "carousel_01.paragraph_02",
    exclusiveOffer: "carousel_01.exclusiveOffer",
  },
];

export const cartList = [
  {
    _id: "1",
    image: Product_01,
    title: "Lenovo Legion 5",
    unitPrice: "10.00$",
    quantity: "1",
  },
  {
    _id: "2",
    image: Product_02,
    title: "VR HeadSet",
    unitPrice: "10.00$",
    quantity: "1",
  },
  {
    _id: "3",
    image: Product_04,
    title: "Geforce Rtx 3090 24GB",
    unitPrice: "1320.50$",
    quantity: "2",
  },
];
